In [1]:
import numpy as np
import pandas as pd

import requests
from bs4 import BeautifulSoup

In [2]:
def get_web_page(url):
    resp = requests.get(url)
    resp.encoding = 'utf-8'
    
    if resp.status_code != 200:
        print('Invalid url:', resp.url)
        return None
    else:
        return resp.text

In [13]:
    if __name__ == "__main__":
        #第一段是針對我們所需要的網站區塊作的連結
        url='https://www.vgchartz.com/games/games.php?page=3&results=200&name=&console=Wii&keyword=&publisher=&genre=&order=TotalShipped&ownership=Both&boxart=Both&banner=Both&showdeleted=&region=All&goty_year=&developer=&direction=DESC&showtotalsales=0&shownasales=0&showpalsales=0&showjapansales=0&showothersales=0&showpublisher=1&showdeveloper=0&showreleasedate=1&showlastupdate=1&showvgchartzscore=1&showcriticscore=1&showuserscore=1&showshipped=1&alphasort=&showmultiplat=No'
        rate_page = get_web_page(url)
        soup = BeautifulSoup(rate_page, 'html.parser')
        rate_list = soup.find_all('tr')[27:227] # table rows for storing the rates #這一行是爬遊戲評分的數據
        odd_trs = soup.find_all('tr', style='background-image:url(../imgs/chartBar_large.gif); height:70px')#這兩行是爬遊戲名稱的區塊
        even_trs = soup.find_all('tr', style='background-image:url(../imgs/chartBar_alt_large.gif); height:70px')
        
        #創建儲存資料的地方
        games_name= []
        VGChartz_Score = []
        Critic_Score = []
        User_Score = []
        total_shipped = []
        
        #把爬到的數據丟進儲存資料
        for data in rate_list:
            row = data.find_all('td', align='center')
            VGChartz_Score.append(row[1].text.strip())
            Critic_Score.append(row[2].text.strip())
            User_Score.append(row[3].text.strip())
            total_shipped.append(row[4].text.strip())
        
        #把爬到的遊戲名稱丟進儲存資料
        for i in range(len(odd_trs)):
            odd_game_name = odd_trs[i].find('td', style='font-size:12pt;').text.strip()
            even_game_name = even_trs[i].find('td', style='font-size:12pt;').text.strip()
    
            games_name.append(odd_game_name)
            games_name.append(even_game_name)     
        
        #把儲存資料轉換成dataframe
        rate_df = pd.DataFrame({
            'Game_Name': games_name,
            'VGChartz_Score': VGChartz_Score,
            'Critic_Score': Critic_Score,
            'User_Score': User_Score,
            'Total_Shipped': total_shipped
        })

In [16]:
#把dataframe輸出成excel檔
outputpath='遊戲評分_wii_3.xlsx'
rate_df.to_excel(outputpath,index=False,header=False)

In [15]:
rate_df.head()

,Game_Name,VGChartz_Score,Critic_Score,User_Score,Total_Shipped
0,GT Pro Series,N/A,3.7,N/A,N/A
1,Dragon Quest X,N/A,N/A,N/A,N/A
2,Star Wars: The Force Unleashed II,N/A,7.5,N/A,N/A
3,Tom Clancy's HAWX,N/A,N/A,N/A,N/A
4,Winter Sports 2011,N/A,N/A,N/A,N/A

In [50]:
pd.read_excel('遊戲評分.xlsx')

                               Final Fantasy II  N/A  10.0  N/A.1
0                                   Final Fight  NaN  10.0    NaN
1                               Forza Horizon 4  NaN  10.0    NaN
2                               Fusion: Genesis  NaN  10.0    NaN
3                                     Minecraft  NaN  10.0    NaN
4         Red Dead Redemption: Undead Nightmare  NaN  10.0    NaN
..                                          ...  ...   ...    ...
244               Pok�mon Gold / Silver Version  NaN   9.2    NaN
245                                   Max Payne  NaN   9.2    NaN
246                            Skies of Arcadia  NaN   9.2    NaN
247  Super Smash Bros. Brawl    Read the review  9.2   9.2    9.7
248                      All-Star Baseball 2001  NaN   9.2    NaN

[249 rows x 4 columns]